name: vr2p
dependencies:
  - python=3.8
  - numpy=1.22.1
  - pandas=1.4.0
  - numba
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - jupyterlab
  - colorcet
  - ipyfilechooser
  - pyyaml
  - h5py
  - conda-forge::gcsfs  
  - conda-forge::zarr=2.8.1
  - conda-forge::jupyterlab
  - pip
  - pip:
    - napari[all]
    - pirt==2.1.0       # newer version compared to conda available version
    - ipympl